namespace AoC2024.Day08;

public static partial class Day08 {
    public static IEnumerable<SampleInput> GetSamples() {
        yield return SampleInput.ForInput(
                """
                ............
                ........0...
                .....0......
                .......0....
                ....0.......
                ......A.....
                ............
                ............
                ........A...
                .........A..
                ............
                ............
                """
            ).WithPartOneAnswer(14)
            .WithPartTwoAnswer(34);
    }
}
