namespace AoC2022.Day23;

public partial class Day23 {
    public static IEnumerable<SampleInput> GetSamples() {
        yield return SampleInput.ForInput("""
                                          ..............
                                          ..............
                                          .......#......
                                          .....###.#....
                                          ...#...#.#....
                                          ....#...##....
                                          ...#.###......
                                          ...##.#.##....
                                          ....#..#......
                                          ..............
                                          ..............
                                          ..............
                                          """)
            .WithPartOneAnswer("110")
            .WithPartTwoAnswer("20");
    }
}